name: Deploy to Hostinger

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Push to build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: .
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
          MESSAGE: "Deploy: {sha}"
        with:
          debug: true
          skip-if-unchanged: false
